### ISSUE TITLE
I got this error while building aries max android project

### ISSUE THREAD

**Issue by rkirandas** [hyperledger/aries-mobile-agent-xamarin#61]
As Instructed in Readme's  step 5.Open aries-max-app.sln and build  then got this error 

Error		System.InvalidOperationException: Duplicate attribute.
   at System.Xml.Linq.XElement.AddAttributeSkipNotify(XAttribute a)
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at System.Xml.Linq.XContainer.Add(Object content)
   at Xamarin.Android.Tasks.ManifestDocument.AddLauncherIntentElements(XElement activity)
   at Xamarin.Android.Tasks.ManifestDocument.<>c__DisplayClass99_0.<ActivityFromTypeDefinition>b__1(ActivityAttribute aa, XElement element)
   at Xamarin.Android.Tasks.ManifestDocument.ToElement[TAttribute](TypeDefinition type, String name, Func`2 parser, Func`2 toElement, Action`2 update)
   at Xamarin.Android.Tasks.ManifestDocument.ActivityFromTypeDefinition(TypeDefinition type, String name, Int32 targetSdkVersion)
   at Xamarin.Android.Tasks.ManifestDocument.Merge(TaskLoggingHelper log, TypeDefinitionCache cache, List`1 subclasses, String applicationClass, Boolean embed, String bundledWearApplicationName, IEnumerable`1 mergedManifestDocuments)
   at Xamarin.Android.Tasks.GenerateJavaStubs.Run(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.GenerateJavaStubs.RunTask()
   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/builder/azdo/_work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17	Hyperledger.Aries.Max.Android

**Comment by x0axz** [comment]
Have a look https://github.com/xamarin/xamarin-android/issues/6463#issuecomment-959992396

**Comment by rkirandas** [comment]
Before Closing this issue

Is there any walkthrough or guide to setup a cloud agent using Aries dotnet to create an issuer like Faber college / a verifier like acme and the Aries Max as Alice.

Any help would be appreciated

**Comment by x0axz** [comment]
Yes, there is, however I'd propose closing this issue and opening a new one in the [aries-framework-dotnet](https://github.com/hyperledger/aries-framework-dotnet) repository to ask the same topic, as it might assist someone else.

**Comment by rkirandas** [comment]
@x0axz  Did as you mentioned.

Looking forward for the answer

**Comment by x0axz** [comment]
Here it is: https://github.com/hyperledger/aries-framework-dotnet/issues/225#issuecomment-1145673868
